/* Английский словарь игры. Ключ — русская строка из кода или данных, значение —
   то, что увидит игрок на неподдерживаемом языке. Подстановки идут через {имя}.
   Полноту словаря проверяет tests/i18n.mjs: новая русская строка без пары падает. */
export const EN = {
  // ─── Транспорт ───
  'легковая': 'car',
  'машину': 'the car',
  'легковые': 'cars',
  'мотоцикл': 'motorbike',
  'мотоциклы': 'motorbikes',
  'фура': 'truck',
  'фуру': 'the truck',
  'фуры': 'trucks',
  'автобус': 'bus',
  'автобусы': 'buses',
  'Мотоцикл: бак маленький и денег мало, зато уедет быстро — если успеете.': 'Motorbike: small tank, small money — but it is gone fast, if you are.',
  'Фура идёт на третий пост: заправка долгая, но платит вдвое.': 'A truck takes the third bay: a long fill, but it pays double.',
  'Автобус: пока стоит под заправкой, из него выйдет целый салон.': 'A bus: while it fuels, a whole cabin walks into the shop.',

  // ─── Смены ───
  'Бесконечная ночь {n}': 'Endless night {n}',
  'Цели нет — работайте, пока не рассветёт, и держите репутацию.': 'No goal — work until dawn and keep your rating up.',
  'Наплыв': 'Rush',

  // ─── Улучшения станции ───
  'Рабочие ботинки': 'Work boots',
  'Ходить по станции на 18% быстрее': 'Walk the lot 18% faster',
  'Первое, на что тратят ночную выручку: между колонкой и прилавком бегать всю ночь.': 'The first thing night takings buy: you spend the night running between the pump and the counter.',
  'Вторая кофемашина': 'Second coffee machine',
  'Кофе готовится вдвое быстрее': 'Coffee brews twice as fast',
  'Вторая машина на прилавке: два стакана варятся разом, очередь у кассы тает.': 'A second machine on the counter: two cups at once, and the queue at the till melts.',
  'Прожекторы над площадкой': 'Floodlights over the lot',
  'Клиенты ждут на 12% дольше': 'Customers wait 12% longer',
  'Свет на мачтах по краям площадки. Видно, что работа идёт, и ждут спокойнее.': 'Lights on masts at both edges of the lot. People can see the place is working, and they wait easier.',
  'Щит на трассе': 'Roadside sign',
  'Машины сворачивают к вам чаще': 'More cars turn in',
  'Подсвеченный щит у дороги. Ночью его видно за километр — поток плотнее.': 'A lit board by the road. At night you can see it a kilometre away — the traffic thickens.',
  'Скоростные насосы': 'Fast pumps',
  'Заправка на четверть быстрее': 'Fuelling a quarter faster',
  'Новые пистолеты на всех постах: бак наполняется заметно быстрее.': 'New nozzles on every bay: the tank fills noticeably quicker.',
  'Третий пост навсегда': 'The third bay for good',
  'Левый пост открыт каждую ночь': 'The left bay opens every night',
  'Пост выкуплен насовсем. Не работает только в те ночи, когда колонки закрыты аварией.': 'The bay is bought outright. It stays shut only on the nights a breakdown closes the pumps.',
  'Тележка для коробок': 'Box cart',
  'Один подъём на склад пополняет все запасы': 'One trip upstairs refills everything',
  'Тележка у стеллажей: грузите на неё всё, что кончилось, и спускаетесь один раз.': 'A cart by the shelves: load everything that ran out and come down once.',

  // ─── Витрина магазина ───
  'кофе': 'coffee',
  'сэндвич': 'sandwich',
  'хот-дог': 'hot dog',
  'газировка': 'soda',
  'газировку': 'soda',
  'сэндвичей': 'sandwiches',
  'хот-догов': 'hot dogs',
  'газировки': 'soda',
  'КОФЕ': 'COFFEE',
  'СЭНДВИЧИ': 'SANDWICHES',
  'ХОТ-ДОГИ': 'HOT DOGS',
  'ГАЗИРОВКА': 'SODA',
  'Кофе закончился': 'Coffee has run out',
  'Кофемашина и так полная': 'The coffee machine is already full',
  'Пополните кофемашину': 'Refill the coffee machine',
  'Еда закончилась': 'The food is gone',
  'Витрина и так полная': 'The display is already full',
  'Пополните витрину сэндвичей': 'Refill the sandwich display',
  'Хот-доги закончились': 'Hot dogs have run out',
  'Гриль и так полный': 'The grill is already full',
  'Пополните гриль': 'Refill the grill',
  'Газировка закончилась': 'Soda has run out',
  'Холодильник и так полный': 'The fridge is already full',
  'Пополните холодильник': 'Refill the fridge',
  'Склад на 2 этаже · лестница снаружи справа': 'Stock room upstairs · stairs outside on the right',

  // ─── Главы и погода ───
  'Первые ночи': 'First nights',
  'Колонка, пистолет и один клиент за раз': 'One pump, one nozzle, one customer at a time',
  'Магазин': 'The shop',
  'Кофе, сэндвичи и склад на втором этаже': 'Coffee, sandwiches and the stock room upstairs',
  'Три поста': 'Three bays',
  'Очередь, левая колонка и те, кто спешит': 'The queue, the left pump and the ones in a hurry',
  'Железо': 'Hardware',
  'Колонки ломаются, а топливо привозят по ночам': 'Pumps break down and fuel arrives at night',
  'Темнота': 'Darkness',
  'Свет гаснет, а трасса не ждёт': 'The lights go out and the road does not wait',
  'Хаос': 'Chaos',
  'Всё сразу и до самого рассвета': 'Everything at once, all the way to dawn',
  'Ясно': 'Clear',
  'ясно': 'clear',
  'Дождь': 'Rain',
  'дождь': 'rain',
  'Идёт дождь: с колёс на пол несут грязь.': 'It is raining: wheels track dirt onto the floor.',
  'Туман': 'Fog',
  'туман': 'fog',
  'Станцию затянуло туманом — фары видно в последний момент.': 'Fog has settled over the station — headlights show up at the last moment.',

  // ─── Цели ночи ───
  'Обслужено': 'Served',
  'Обслужить {n} машин': 'Serve {n} cars',
  'Обслужено {served} из {target} машин': 'Served {served} of {target} cars',
  'Выручка': 'Takings',
  'Заработать ₽{n}': 'Earn ₽{n}',
  'Заработано ₽{earned} из ₽{target}': 'Earned ₽{earned} of ₽{target}',
  'Репутация': 'Rating',
  'Удержать репутацию {n}★': 'Keep a rating of {n}★',
  'Репутация {rep}★ ниже нужных {target}★': 'Rating {rep}★ is below the required {target}★',
  'Потеряно': 'Lost',
  'Не упустить ни одного клиента': 'Do not lose a single customer',
  'Упустить не больше {n} клиентов': 'Lose no more than {n} customers',
  'Упущено клиентов: {lost}, допустимо {target}': 'Customers lost: {lost}, allowed {target}',

  // ─── Ночи кампании ───
  'Первая заправка': 'First fill-up',
  'Снимите пистолет с колонки, заправьте машину и проводите её. Кто-то заодно попросит кофе: аппарат стоит на прилавке в магазине.': 'Take the nozzle off the pump, fill the car and see it off. Somebody will ask for coffee too: the machine is on the counter inside the shop.',
  'Ритм колонки': 'The pump\'s rhythm',
  'Машины пошли чаще, и кофе просят почти в каждой. Колонка и прилавок теперь спорят за вас.': 'Cars come more often, and nearly every one asks for coffee. The pump and the counter now fight over you.',
  'Кофе для дальнобойщика': 'Coffee for the trucker',
  'Из машины выходит не только водитель: бывает, к прилавку встают сразу двое, и ждать они будут каждый своё.': 'More than the driver steps out: sometimes two people come to the counter, and each waits for an order of their own.',
  'Дождь над трассой': 'Rain over the road',
  'Первый дождь за смену: с колёс несут грязь. Пока на полу пятно, за прилавком не обслуживают — швабра важнее кофе.': 'The first rain of the shift: wheels bring in dirt. While there is a spill on the floor the counter serves nobody — the mop matters more than coffee.',
  'Ночь без пауз': 'A night without pauses',
  'Экзамен первой главы: поток не прерывается, а в середине ночи придёт колонна.': 'Chapter one exam: the flow never breaks, and a convoy arrives in the middle of the night.',
  'Колонна с трассы': 'Convoy off the road',
  'Сэндвич в дорогу': 'A sandwich for the road',
  'К кофе добавились сэндвичи: витрина стоит на прилавке справа. Заказов теперь два вида, а руки по-прежнему одни.': 'Sandwiches join the coffee: the display stands on the right of the counter. Two kinds of orders now, and still one pair of hands.',
  'Пустая полка': 'Empty shelf',
  'Кофе в аппарате почти нет. Запас всех товаров лежит на складе второго этажа — по наружной лестнице справа.': 'The coffee machine is nearly empty. Stock for everything sits in the upstairs room — up the outside stairs on the right.',
  'Гриль и пустые полки': 'The grill and empty shelves',
  'Полки пустые с самого начала, а на гриле у левой стены пошли хот-доги: их готовят дольше всего, и запас к ним свой.': 'The shelves start empty, and hot dogs are rolling on the grill by the left wall: they take the longest and have stock of their own.',
  'Туман и забытая сумка': 'Fog and a forgotten bag',
  'Туман сел на трассу, а у входа кто-то оставил сумку. Ящик «НАХОДКИ» — справа в магазине.': 'Fog has settled on the road, and somebody left a bag by the door. The LOST & FOUND box is on the right inside the shop.',
  'Перед рассветом': 'Before dawn',
  'Экзамен второй главы: пустые полки, наплыв и никакого запаса времени.': 'Chapter two exam: empty shelves, a rush and no spare time at all.',
  'Автобус на заправке': 'A bus at the station',
  'Двое в очереди': 'Two in line',
  'Теперь в очередь встают двое. Обслуживайте по порядку, первый ждёт дольше всех. Между ними попадаются мотоциклы: бак у них крошечный, а терпение ещё меньше.': 'Two cars queue up now. Serve them in order — the first has waited longest. Motorbikes turn up between them: tiny tanks and even less patience.',
  'Третий пост': 'The third bay',
  'Слева открыли третий пост под собственной мачтой — и первыми на него пошли фуры: под навесом им не развернуться. Стоят долго, платят вдвое.': 'A third bay has opened on the left under its own mast — and trucks took it first: they cannot turn under the canopy. They stand for a long time and pay double.',
  'Кто-то очень спешит': 'Somebody is in a hurry',
  'Часть клиентов сегодня торопится: платят вдвое, но ждут вдвое меньше. Их машины — жёлтые.': 'Some customers are in a hurry tonight: they pay double but wait half as long. Their cars are the yellow ones.',
  'Заказ за заказом': 'Order after order',
  'Третий пост закрыт на профилактику, зато в магазине очередь: к тому же в холодильнике появилась газировка — четвёртый товар и четвёртый стеллаж на складе.': 'The third bay is closed for maintenance, but the shop has a queue: soda has appeared in the fridge as well — a fourth product and a fourth shelf upstairs.',
  'Колонна фур': 'Truck convoy',
  'Экзамен третьей главы: три поста, две волны подряд и колонна фур на левом посту.': 'Chapter three exam: three bays, two waves in a row and a convoy of trucks on the left bay.',
  'Первая волна': 'First wave',
  'Заклинило': 'Jammed',
  'Колонка встанет. Ящик с инструментом — у левой стены магазина.': 'A pump will seize up. The toolbox is by the left wall of the shop.',
  'Одна колонка': 'One pump',
  'Работает только первая колонка. Вся ночь — через неё, очередь будет длинной.': 'Only the first pump works. The whole night goes through it, and the queue will be long.',
  'Приедет бензовоз': 'A tanker is coming',
  'В резервуаре осталось на восемь заправок. Ночью привезут топливо: возьмите рукав и слейте его в горловину слева.': 'The tank holds eight more fills. Fuel arrives during the night: take the hose and drain it into the filler on the left.',
  'Странный фургон': 'The strange van',
  'Ночной автобус: пока он стоит под заправкой, к прилавку выйдет целый салон. А к дальней стоянке подъедет фургон без фар.': 'A night bus: while it fuels, a whole cabin comes to the counter. And a van with no headlights pulls up to the far parking spot.',
  'Всё сразу': 'Everything at once',
  'Экзамен четвёртой главы: поломка, наплыв, пустые полки и приёмка топлива в одну смену.': 'Chapter four exam: a breakdown, a rush, empty shelves and a fuel delivery in one shift.',
  'Ночной наплыв': 'Night rush',
  'Свет мигнул': 'The lights flickered',
  'Ночью вырубит электричество. Без света не работает ничего — сначала щиток.': 'The power will go out tonight. Nothing works without it — the fuse box first.',
  'Во тьме': 'In the dark',
  'Щиток выбьет дважды, и все три поста встанут вместе с ним. Руки держите свободными.': 'The fuse box will blow twice, and all three bays stop with it. Keep your hands free.',
  'Шёпот в тумане': 'A whisper in the fog',
  'Туман, помехи в радио и фургон без фар. Работа при этом не отменяется.': 'Fog, static on the radio and a van with no headlights. The work carries on regardless.',
  'Одна колонка в темноте': 'One pump in the dark',
  'Открыт только первый пост, и свет ненадёжен. Очередь будет длинной.': 'Only the first bay is open, and the power is unreliable. The queue will be long.',
  'Самая длинная ночь': 'The longest night',
  'Экзамен пятой главы: ливень, темнота, поломки, две волны и бензовоз посреди всего этого.': 'Chapter five exam: a downpour, darkness, breakdowns, two waves and a tanker in the middle of it all.',
  'Волна перед рассветом': 'The wave before dawn',
  'Пересменка на карьере': 'Shift change at the quarry',
  'Пересменка на карьере: полки пустые, половина клиентов спешит, а на левый пост одна за другой идут фуры.': 'Shift change at the quarry: the shelves are empty, half the customers are in a hurry, and trucks come to the left bay one after another.',
  'Смена на карьере': 'Quarry shift',
  'Ремонт посреди волны': 'Repairs in mid-wave',
  'Дождь, полная очередь и колонка, которая сломается прямо в наплыв. Чинить или заправлять — решать вам.': 'Rain, a full queue and a pump that breaks right in the rush. Fix it or fuel — your call.',
  'Волна с трассы': 'Wave off the road',
  'Темно и тесно': 'Dark and tight',
  'Один пост, туман до самой трассы и два отключения света за ночь.': 'One bay, fog all the way to the road and two blackouts in a night.',
  'Затор на въезде': 'Jam at the entrance',
  'Ночь всех событий': 'The night of everything',
  'Пятно, сумка, фургон, поломка, темнота и бензовоз. По одному разу и всё за смену.': 'A spill, a bag, the van, a breakdown, darkness and a tanker. Once each, all in one shift.',
  'Ночной поток': 'Night flow',
  'Последняя ночь. Ливень, три волны, темнота, пустой склад и два бензовоза. Дотяните до утра.': 'The last night. A downpour, three waves, darkness, an empty stock room and two tankers. Hold out until morning.',
  'Вторая волна': 'Second wave',
  'Последний рывок': 'The last push',

  // ─── Метки на плитках уровней ───
  '3 поста': '3 bays',
  'один пост': 'one bay',
  'спешат': 'in a hurry',
  'бензовоз': 'tanker',
  'темнота': 'darkness',
  'поломки': 'breakdowns',
  '{n} волны': '{n} waves',
  'наплыв': 'rush',
  'очередь': 'queue',
  'склад': 'stock room',
  'поток заказов': 'order flow',
  'кофе и сэндвичи': 'coffee and sandwiches',
  'основы': 'basics',

  // ─── Достижения ───
  'Первый бак': 'First tank',
  'Заправить первую машину': 'Fuel your first car',
  'Первая ночь': 'First night',
  'Закрыть первую смену': 'Finish your first shift',
  'Бариста': 'Barista',
  'Выдать 25 стаканов кофе': 'Hand over 25 cups of coffee',
  'Ночная кухня': 'Night kitchen',
  'Выдать 25 сэндвичей': 'Hand over 25 sandwiches',
  'Гриль-мастер': 'Grill master',
  'Выдать 20 хот-догов': 'Hand over 20 hot dogs',
  'Холодная полка': 'Cold shelf',
  'Выдать 20 бутылок газировки': 'Hand over 20 sodas',
  'Кладовщик': 'Stock keeper',
  'Десять раз принести запас со склада': 'Bring stock down ten times',
  'Чистый пол': 'Clean floor',
  'Убрать десять пятен': 'Mop ten spills',
  'Механик': 'Mechanic',
  'Починить пять колонок': 'Fix five pumps',
  'Электрик': 'Electrician',
  'Пять раз перезапустить щиток': 'Reset the fuse box five times',
  'Честная находка': 'Honest find',
  'Вернуть пять забытых сумок': 'Return five forgotten bags',
  'Внутри никого': 'Nobody inside',
  'Проверить странный фургон': 'Check the strange van',
  'Приёмка': 'Delivery',
  'Принять пять бензовозов': 'Take five tanker deliveries',
  'Никого не упустил': 'Nobody left',
  'Пройти уровень, не потеряв ни одного клиента': 'Clear a night without losing a customer',
  'Пять безупречных': 'Five clean nights',
  'Пять уровней без потерянных клиентов': 'Five nights without a lost customer',
  'Экзамен без потерь': 'Clean exam',
  'Сдать экзамен, не потеряв ни одного клиента': 'Pass an exam night without losing a customer',
  'Час пик': 'Rush hour',
  'Пережить десять наплывов': 'Survive ten rushes',
  'Не задерживаю': 'No hold-ups',
  'Обслужить 15 спешащих клиентов': 'Serve 15 customers in a hurry',
  'Дальнобой': 'Long haul',
  'Заправить десять фур': 'Fuel ten trucks',
  'Два колеса': 'Two wheels',
  'Заправить 15 мотоциклов': 'Fuel 15 motorbikes',
  'Полный салон': 'Full cabin',
  'Отпустить автобус, выдав все три заказа': 'Send off a bus with all three orders served',
  'Под дождём': 'In the rain',
  'Отработать три смены в дождь': 'Work three shifts in the rain',
  'Свой на трассе': 'A regular on the road',
  'Обслужить 100 клиентов': 'Serve 100 customers',
  'Цистерна': 'Tanker',
  'Заправить 50 машин': 'Fuel 50 cars',
  'Удачная ночь': 'A good night',
  'Заработать ₽800 за одну смену': 'Earn ₽800 in one shift',
  'Касса': 'Takings',
  'Заработать ₽10000 за всё время': 'Earn ₽10000 in total',
  'Пройти главу 1': 'Clear chapter 1',
  'Пройти главу 2': 'Clear chapter 2',
  'Очередь': 'The queue',
  'Пройти главу 3': 'Clear chapter 3',
  'Пройти главу 4': 'Clear chapter 4',
  'Пройти главу 5': 'Clear chapter 5',
  'Пройти главу 6': 'Clear chapter 6',
  'Рассвет': 'Dawn',
  'Пройти все 30 уровней кампании': 'Clear all 30 nights of the campaign',
  'Без конца': 'No end',
  'Отработать три ночи в бесконечном режиме': 'Work three nights in endless mode',
  'Разминка': 'Warm-up',
  'Подпрыгнуть 100 раз': 'Jump 100 times',
  // ─── Предметы в руках и подсказки ───
  'Швабра вернулась на место': 'The mop is back in its place',
  'Инструменты вернулись в ящик': 'The tools are back in the box',
  'Сначала возьмите швабру на складе наверху': 'Take the mop from the stock room upstairs first',
  'Сначала возьмите инструменты на складе наверху': 'Take the tools from the stock room upstairs first',
  'Сначала снимите пистолет с нужной колонки': 'Take the nozzle off the right pump first',
  'Сначала возьмите рукав у бензовоза': 'Take the hose from the tanker first',
  'Кофе': 'Coffee',
  'Сэндвич': 'Sandwich',
  'Хот-дог': 'Hot dog',
  'Газировка': 'Soda',
  'Коробка товара': 'Box of stock',
  'Запас кофе': 'Coffee stock',
  'Запас сэндвичей': 'Sandwich stock',
  'Запас хот-догов': 'Hot dog stock',
  'Запас газировки': 'Soda stock',
  'Тележка с запасом': 'Loaded cart',
  'Забытая сумка': 'Forgotten bag',
  'Швабра': 'Mop',
  'Инструменты': 'Tools',
  'Заправочный пистолет': 'Fuel nozzle',
  'Рукав бензовоза': 'Tanker hose',

  // ─── Загрузка ───
  'Проверяем кофемашину…': 'Checking the coffee machine…',
  'Расставляем товар…': 'Stocking the shelves…',
  'Протираем колонку…': 'Wiping down the pump…',
  'Открываем третий пост…': 'Opening the third bay…',
  'Заводим бензовоз…': 'Starting the tanker…',
  'Включаем фонари…': 'Switching on the lights…',
  'Слушаем тишину…': 'Listening to the quiet…',
  'Считаем сдачу…': 'Counting the change…',
  'Открываем смену…': 'Opening the shift…',

  // ─── Обучение ───
  'Как двигаться': 'How to move',
  'Кликните по игре и осматривайтесь мышью. WASD — движение относительно взгляда, Shift — бег, Space — прыжок, E — действие. На телефоне: левый стик, свайп справа и кнопки «Прыжок» и «Действие».': 'Click the game and look around with the mouse. WASD moves you relative to your view, Shift runs, Space jumps, E acts. On a phone: the left stick, a swipe on the right, and the Jump and Action buttons.',
  'Колонки и машины': 'Pumps and cars',
  'Когда машина остановится, сначала снимите пистолет с отмеченной колонки. Затем подойдите к лючку машины и удерживайте E для заправки. После неё шланг вернётся на место. Пока все посты заняты, остальные ждут в линии у съезда: их терпение тикает так же, как у колонки, и видно в панели дел — не дождавшись, клиент уедет сам.': 'When a car stops, first take the nozzle off the marked pump. Then walk to the car\'s filler and hold E to fuel it. The hose goes back on its own afterwards. While every bay is busy the rest wait in line by the slip road: their patience ticks down just as it does at the pump, and you can see it in the task panel — a customer who gives up drives off.',
  'Магазин и покупатели': 'The shop and its customers',
  'Пока вы заправляете машину, водитель заходит в магазин и встаёт к прилавку. Кофе и сэндвичи — на прилавке, гриль с хот-догами и холодильник — в глубине зала. Приготовьте заказ и выдайте его на кассе, перед тем кто ждёт.': 'While you fuel a car, its driver walks into the shop and stands at the counter. Coffee and sandwiches are on the counter, the grill with hot dogs and the fridge are deeper in the room. Make the order and hand it over at the till, in front of whoever is waiting.',
  'Три поста и топливо': 'Three bays and the fuel',
  'Слева работает третий пост: туда встаёт машина, когда первые два заняты. На некоторых уровнях считают топливо в резервуаре — когда оно кончится, заправлять будет нечем. Приедет бензовоз: возьмите у него рукав и слейте топливо в горловину рядом.': 'A third bay works on the left: a car goes there when the first two are busy. On some nights the fuel in the tank is counted — when it runs dry there is nothing to pump. A tanker will arrive: take its hose and drain the fuel into the filler beside it.',
  'Кто приехал': 'Who drove in',
  'Ночью приезжают не только легковые. Мотоцикл заправляется за пару секунд, но и ждать почти не станет — денег с него мало. Фура стоит у колонки дольше всех и платит вдвое: ей нужен третий пост слева, между колонками под навесом ей не развернуться. Автобус привозит в магазин сразу три заказа и не уедет, пока не обслужат последнего.': 'Not only cars come at night. A motorbike fuels in a couple of seconds but will barely wait — and there is little money in it. A truck stands longest and pays double: it needs the third bay on the left, it cannot turn between the pumps under the canopy. A bus brings three orders into the shop at once and will not leave until the last one is served.',
  'Склад наверху': 'The stock room upstairs',
  'Всё, чем торгует прилавок, и весь инвентарь лежат на складе второго этажа: выйдите на улицу, поднимитесь по лестнице справа от магазина, и дверь откроется сама. У каждого стеллажа своя лента — кофе, сэндвичи, хот-доги, газировка. У самой двери стоят верстак с инструментом и швабра с ведром. Коробку можно взять заранее, пока нет очереди, а инструмент со шваброй — до того, как что-нибудь случится.': 'Everything the counter sells, and all the equipment, sits in the upstairs room: step outside, take the stairs to the right of the shop, and the door opens by itself. Each shelf has its own colour — coffee, sandwiches, hot dogs, soda. By the door stand the workbench with the tools and the mop with its bucket. Take a box in advance while there is no queue, and the tools and the mop before anything happens.',
  'Станция растёт': 'The station grows',
  'Ночная выручка остаётся на станции. В меню и на экране итогов есть раздел «СТАНЦИЯ»: там за деньги выкупаются вторая кофемашина, прожекторы над площадкой, щит на трассе, скоростные насосы, третий пост навсегда и тележка для коробок. Покупка одна и навсегда — её видно на площадке и слышно по работе, а работать лучше, чем «на зачёт», становится выгодно.': 'Night takings stay at the station. The menu and the results screen both have a STATION section: there the money buys a second coffee machine, floodlights over the lot, a roadside sign, fast pumps, the third bay for good and a cart for the boxes. Each purchase is made once and stays — you can see it on the lot and hear it in the work, and doing better than "just enough" starts to pay.',
  'Цель ночи': 'The goal of the night',
  'У каждого уровня своя цель: обслужить столько-то машин, заработать сумму, удержать репутацию или не упустить клиентов. Прогресс виден в панели дел слева. За минуту до конца небо начинает светлеть, а звёзды гаснут — сколько осталось, видно и без часов. Если цель не выполнена, уровень можно переиграть: деньги и выкупленное на станции остаются.': 'Every night has its own goal: serve so many cars, earn a sum, keep your rating up or not lose customers. Progress is in the task panel on the left. A minute before the end the sky starts to lighten and the stars go out — you can see how much is left without the clock. If the goal is missed the night can be replayed: the money and everything bought at the station stay.',
  'Ночные происшествия': 'Things that happen at night',
  'При отключении света вся заправка остановится: поднимитесь на склад за инструментом и почините щиток у левой стены магазина. Входные двери аварийно останутся открыты. Пролитый кофе закрывает прилавок: пока пол липкий, заказы не готовят и не выдают, так что за шваброй придётся идти сразу. Жёлтый ящик «НАХОДКИ» стоит справа от входа.': 'When the power goes out the whole station stops: go up to the stock room for the tools and fix the fuse box by the left wall of the shop. The entrance doors stay open on the emergency release. Spilled coffee closes the counter: while the floor is sticky no orders are made or handed over, so the mop cannot wait. The yellow LOST & FOUND box stands to the right of the entrance.',

  // ─── Надписи на площадке ───
  'ГРИЛЬ': 'GRILL',
  'ЩИТОК': 'FUSE BOX',
  'НАХОДКИ': 'LOST & FOUND',
  'КАССА': 'TILL',
  'СКЛАД ↑': 'STOCK ↑',
  'ИНСТРУМЕНТЫ': 'TOOLS',
  'УБОРКА': 'CLEANING',
  'ПОСТ 3': 'BAY 3',
  'РЕЗЕРВУАР': 'FUEL TANK',
  'ЗАКРЫТО': 'CLOSED',

  // ─── Задания у колонки и в магазине ───
  'В очереди ждёт {vehicle}': 'Waiting in line: {vehicle}',
  'Освободите колонку — иначе уедет, не дождавшись': 'Free up a pump — or they give up and leave',
  '<b>Клиент не дождался очереди</b>': '<b>A customer gave up on the queue</b>',
  '<b>Очередь тоже ждёт</b> — терпение тикает и до колонки': '<b>The line waits too</b> — patience ticks before the pump as well',
  '<b>Клиент торопится</b> — платит вдвое, но ждёт вдвое меньше': '<b>This one is in a hurry</b> — pays double, waits half as long',
  'Возьмите пистолет колонки {n}': 'Take the nozzle from pump {n}',
  'Клиент торопится — шланг с колонки и бегом': 'The customer is in a hurry — grab the hose and run',
  'У колонки {n} ждёт {vehicle}': 'A {vehicle} is waiting at pump {n}',
  'Заправьте {vehicle}': 'Fill up {vehicle}',
  'Встаньте у лючка и направьте пистолет · колонка {n}': 'Stand at the filler and aim the nozzle · pump {n}',
  'Полный бак <b>+₽{gain}</b>': 'Tank full <b>+₽{gain}</b>',
  'У прилавка просят <b>{item}</b>': 'Someone at the counter wants <b>{item}</b>',
  'Приготовьте {item}': 'Make {item}',
  'Заказ у прилавка · {chip} {have}/{max}': 'Counter order · {chip} {have}/{max}',
  '{gone} — нужен запас': '{gone} — stock needed',
  'Выдайте {item}': 'Hand over {item}',
  'Покупатель ждёт у кассы': 'The customer is waiting at the till',
  'Заказ выдан <b>+₽{gain}</b>': 'Order handed over <b>+₽{gain}</b>',
  'Возьмите запас {label}': 'Take stock of {label}',
  'Верните запас {label} на место': 'Put the {label} stock back',
  'Разгрузите тележку': 'Unload the cart',
  'Вниз, к прилавку · коробок: {n}': 'Down to the counter · boxes: {n}',
  'Тележка разгружена: <b>{n}</b> запаса': 'Cart unloaded: <b>{n}</b> restocked',
  'Вернитесь на 1 этаж, к прилавку': 'Go back downstairs to the counter',
  'Аппарат ждёт в зале': 'The machine is waiting in the shop',
  '<b>Клиент уехал недовольным</b>': '<b>A customer left unhappy</b>',
  '…и ещё {n}': '…and {n} more',
  'Всё спокойно': 'All quiet',
  'Осмотритесь вокруг': 'Look around',
  'Направьте пистолет на лючок': 'Aim the nozzle at the filler',
  'Нет электричества — сначала почините щиток': 'No power — fix the fuse box first',
  'Липкий пол — сначала уберите пятно': 'Sticky floor — mop the spill first',
  'В резервуаре пусто — ждите бензовоз': 'The tank is empty — wait for the tanker',
  'Удерживайте для действия': 'Hold to act',
  'Сначала отдайте то, что уже в руках': 'Put down what you are holding first',
  'Уборочный инвентарь у двери склада': 'Cleaning kit by the stock room door',
  'Верните швабру': 'Put the mop back',
  'Возьмите швабру': 'Take the mop',
  'Верстак у двери склада': 'Workbench by the stock room door',
  'Уберите инструменты': 'Put the tools away',
  'Возьмите инструменты': 'Take the tools',

  // ─── Ночные происшествия ───
  'Кто-то разлил кофе': 'Somebody spilled coffee',
  'Пока пол липкий, за прилавком не обслуживают. Швабра с ведром стоит на складе, у двери.': 'While the floor is sticky the counter serves nobody. The mop and bucket are in the stock room by the door.',
  'Уберите пятно': 'Mop the spill',
  'Швабра — на складе, у двери': 'The mop is in the stock room, by the door',
  'Чисто! <b>+₽45</b>': 'Clean! <b>+₽45</b>',
  'Отключился свет': 'The power went out',
  'Вся заправка обесточена. Инструменты — на складе наверху, щиток — у левой стены магазина.': 'The whole station is dead. The tools are in the stock room upstairs, the fuse box is by the left wall of the shop.',
  'Перезапустите щиток': 'Reset the fuse box',
  'Без света не работают ни колонки, ни прилавок': 'Without power neither the pumps nor the counter work',
  'Электричество вернулось <b>+₽35</b>': 'The power is back <b>+₽35</b>',
  'Хозяина не видно. Отнесите её к табличке «НАХОДКИ».': 'The owner is nowhere in sight. Take it to the LOST & FOUND sign.',
  'Подберите сумку': 'Pick up the bag',
  'Она появилась у входа': 'It turned up by the entrance',
  'Отнесите сумку': 'Take the bag over',
  'В жёлтый ящик под табличкой «НАХОДКИ»': 'Into the yellow box under the LOST & FOUND sign',
  'Честность замечена <b>+репутация</b>': 'Honesty noticed <b>+rating</b>',
  'Заклинило колонку': 'A pump has jammed',
  'Пахнет проводкой, но искр пока нет. Ящик с инструментом стоит на верстаке склада.': 'It smells of wiring, no sparks yet. The toolbox is on the workbench upstairs.',
  'Почините колонку {n}': 'Fix pump {n}',
  'Ящик с инструментом — на верстаке склада': 'The toolbox is on the workbench upstairs',
  'Колонка снова работает <b>+₽65</b>': 'The pump works again <b>+₽65</b>',
  'Подозрительный фургон': 'A suspicious van',
  'Он подъехал без фар. Номер заляпан чем-то похожим на пепел.': 'It pulled up with no headlights. The plate is smeared with something like ash.',
  'Проверьте странный фургон': 'Check the strange van',
  'Водитель молчит и не открывает окно': 'The driver says nothing and will not open the window',
  'На сиденье лежал чек с завтрашней датой. Вы получили ₽90.': 'A receipt dated tomorrow lay on the seat. You got ₽90.',
  'Приехал бензовоз': 'The tanker has arrived',
  'Возьмите рукав у цистерны и слейте топливо в горловину резервуара. Третий пост пока занят.': 'Take the hose from the tanker and drain the fuel into the tank filler. The third bay is taken for now.',
  'ПРИЁМКА ТОПЛИВА': 'FUEL DELIVERY',
  'Третий пост закрывают — <b>ждём бензовоз</b>': 'The third bay is closing — <b>a tanker is due</b>',
  'Возьмите рукав бензовоза': 'Take the tanker hose',
  'Шкаф с рукавом — со стороны станции': 'The hose locker is on the station side',
  'Слейте топливо в резервуар': 'Drain the fuel into the tank',
  'Горловина — в бетонной площадке слева': 'The filler is in the concrete pad on the left',
  'Топливо принято <b>+₽{gain}</b>': 'Fuel accepted <b>+₽{gain}</b>',
  '<b>Бензовоз уехал</b> — топливо не приняли': '<b>The tanker left</b> — the fuel was not taken',
  'Резервуар пуст': 'The tank is empty',
  'Заправлять нечем. Дождитесь бензовоза и слейте топливо в горловину слева.': 'Nothing left to pump. Wait for the tanker and drain the fuel into the filler on the left.',
  'ТОПЛИВО': 'FUEL',
  'Топлива осталось на <b>{n}</b> заправки': 'Fuel left for <b>{n}</b> fills',
  'Радио поймало помеху': 'Static on the radio',
  'Сквозь шум кто-то назвал ваше имя. Наверное, дальнобойщики шутят.': 'Through the noise somebody said your name. Truckers messing about, probably.',
  'НОЧНОЕ СОБЫТИЕ': 'NIGHT EVENT',
  'Машины идут одна за другой. Не давайте очереди встать.': 'Cars come one after another. Do not let the queue stall.',
  'НАПЛЫВ МАШИН': 'A RUSH OF CARS',

  // ─── Меню, станция и итоги ───
  'В ИГРУ →': 'PLAY →',
  'ДАЛЬШЕ →': 'NEXT →',
  'Реклама не загрузилась — надбавка не начислена': 'The ad did not load — no bonus added',
  'Надбавка за смену: <b>+₽{bonus}</b>': 'Shift bonus: <b>+₽{bonus}</b>',
  'выкуплено {owned} из {total}': '{owned} of {total} bought',
  'КУПЛЕНО': 'BOUGHT',
  'С {n}-й ночи': 'From night {n}',
  '<b>{name}</b> — станция стала лучше': '<b>{name}</b> — the station got better',
  'Можно выкупить: {n}': 'Available to buy: {n}',
  'Посмотреть, что можно выкупить': 'See what you can buy',
  'Заработанное остаётся на станции': 'What you earn stays at the station',
  '{owned} из {total}': '{owned} of {total}',
  'пройдено {cleared} из {total}': '{cleared} of {total} cleared',
  'Откроется после предыдущей ночи': 'Opens after the previous night',
  'ЭКЗАМЕН': 'EXAM',
  'ГЛАВА {n}': 'CHAPTER {n}',
  'Цель: {goals}.': 'Goal: {goals}.',
  'Цель: доработать до рассвета.': 'Goal: make it to dawn.',
  'ЭКЗАМЕН ГЛАВЫ': 'CHAPTER EXAM',
  'ЗАДАНИЕ НА НОЧЬ': 'TONIGHT’S BRIEF',
  'Глава {n}. {title}': 'Chapter {n}. {title}',
  'экзамен': 'exam',
  'Режим': 'Mode',
  'Без цели': 'No goal',
  '<b>Смена сорвана:</b> {reason}': '<b>Shift ruined:</b> {reason}',
  'БЕСКОНЕЧНАЯ · {n}': 'ENDLESS · {n}',
  'УРОВЕНЬ {n} / {total}': 'LEVEL {n} / {total}',
  'ЗАВЕРШИТЬ КАМПАНИЮ': 'FINISH THE CAMPAIGN',
  'СЛЕДУЮЩАЯ НОЧЬ': 'NEXT NIGHT',
  'СЛЕДУЮЩИЙ УРОВЕНЬ': 'NEXT LEVEL',
  'ПОВТОРИТЬ УРОВЕНЬ': 'REPLAY LEVEL',
  'СМОТРЕТЬ РЕКЛАМУ: +₽{n}': 'WATCH AN AD: +₽{n}',
  'РАССВЕТ · БЕСКОНЕЧНЫЙ РЕЖИМ': 'DAWN · ENDLESS MODE',
  'УРОВЕНЬ {n} ПРОЙДЕН': 'LEVEL {n} CLEARED',
  'УРОВЕНЬ {n} НЕ ЗАЧТЁН': 'LEVEL {n} NOT PASSED',
  'Последняя ночь позади.': 'The last night is behind you.',
  'Ночь закрыта.': 'The night is closed.',
  '{name} — сдано.': '{name} — passed.',
  '{name} — ещё раз.': '{name} — once more.',
  '{failures}. Попробуйте ещё раз — прогресс и деньги остаются.': '{failures}. Try again — progress and money stay.',
  'ЗВУК: ВКЛ': 'SOUND: ON',
  'ЗВУК: ВЫКЛ': 'SOUND: OFF',
  'Не удалось загрузить смену. Обновите страницу.': 'The shift could not be loaded. Refresh the page.',
  // ─── Разметка: шапка, меню, экраны ───
  'Ночная заправка 3D': 'Night Gas Station 3D',
  'Игровая сцена': 'Game scene',
  'НОЧНАЯ ЗАПРАВКА': 'NIGHT GAS STATION',
  'СМЕНА 1': 'SHIFT 1',
  'Краткое обучение': 'Quick guide',
  'ОБУЧЕНИЕ': 'GUIDE',
  'Пауза': 'Pause',
  'УРОВЕНЬ': 'LEVEL',
  '1. Первая заправка': '1. First fill-up',
  'Цель уровня': 'Level goal',
  'ТЕКУЩИЕ ДЕЛА': 'CURRENT TASKS',
  'Запасы магазина': 'Shop stock',
  'Взаимодействовать': 'Interact',
  'В руках:': 'Holding:',
  'КЛИКНИТЕ ПО ИГРЕ, ЧТОБЫ ОСМАТРИВАТЬСЯ': 'CLICK THE GAME TO LOOK AROUND',
  'Прыжок': 'Jump',
  'ПРЫЖОК': 'JUMP',
  'ДЕЙСТВИЕ': 'ACTION',
  'НОЧНАЯ': 'NIGHT',
  'ЗАПРАВКА': 'GAS STATION',
  'Зажигаем вывеску…': 'Lighting the sign…',
  'ТРАССА М-13 · 02:47': 'HIGHWAY M-13 · 02:47',
  'Обычная работа. Необычные посетители.': 'Ordinary work. Unusual visitors.',
  'Главное — дотянуть до рассвета.': 'Just make it to dawn.',
  'ПРОДОЛЖИТЬ СМЕНУ': 'CONTINUE SHIFT',
  'УРОВНИ': 'LEVELS',
  'СТАНЦИЯ': 'STATION',
  'ДОСТИЖЕНИЯ': 'ACHIEVEMENTS',
  'НОВАЯ ИГРА': 'NEW GAME',
  'двигаться': 'move',
  'действие': 'action',
  'бег': 'run',
  'прыжок': 'jump',
  'ПЕРВАЯ СМЕНА': 'FIRST SHIFT',
  'Добро пожаловать': 'Welcome',
  'на ночную.': 'to the night shift.',
  'Осматривайся мышью, ходи на': 'Look around with the mouse, walk with',
  ', прыгай на': ', jump with',
  'Подойди к цели и удерживай': 'Walk up to a task and hold',
  'Цель ночи — слева, в панели дел. Не выполнил — уровень повторяется': 'The goal is on the left, in the task panel. Miss it and the night repeats',
  'Здесь бывает странно, но по-настоящему опасно — почти никогда.': 'It gets strange here, but genuinely dangerous — almost never.',
  'ОТКРЫТЬ СМЕНУ': 'OPEN THE SHIFT',
  'КРАТКОЕ ОБУЧЕНИЕ': 'QUICK GUIDE',
  'Закрыть': 'Close',
  'Кликните по игре и осматривайтесь мышью. WASD — движение, Shift — бег, E — действие.': 'Click the game and look around with the mouse. WASD moves, Shift runs, E acts.',
  '← НАЗАД': '← BACK',
  'ВЫБОР УРОВНЯ ·': 'LEVEL SELECT ·',
  'пройдено 0 из 30': '0 of 30 cleared',
  'БЕСКОНЕЧНЫЙ РЕЖИМ': 'ENDLESS MODE',
  'СТАНЦИЯ ·': 'STATION ·',
  'В кассе': 'In the till',
  '· улучшения покупаются навсегда и работают со следующей ночи': '· upgrades are bought for good and work from the next night',
  'ДОСТИЖЕНИЯ ·': 'ACHIEVEMENTS ·',
  'ПЕРЕРЫВ': 'BREAK',
  'Смена на паузе': 'Shift paused',
  'ПРОДОЛЖИТЬ': 'RESUME',
  'ГРОМКОСТЬ МУЗЫКИ': 'MUSIC VOLUME',
  'Громкость музыки': 'Music volume',
  'В главное меню': 'To the main menu',
  'РАССВЕТ · СМЕНА ЗАКРЫТА': 'DAWN · SHIFT CLOSED',
  'Неплохая ночка.': 'Not a bad night.',
  'ЗАРАБОТАНО': 'EARNED',
  'ОБСЛУЖЕНО': 'SERVED',
  'РЕПУТАЦИЯ': 'RATING',
  'РЕКОРД': 'BEST',
  'СМОТРЕТЬ РЕКЛАМУ: НАДБАВКА К ЗАРАБОТКУ': 'WATCH AN AD: BONUS TO YOUR TAKINGS',
  'СЛЕДУЮЩАЯ СМЕНА': 'NEXT SHIFT',
  'Выбрать другой уровень': 'Pick another level',
  'РАССВЕТ · КАМПАНИЯ ЗАВЕРШЕНА': 'DAWN · CAMPAIGN COMPLETE',
  'Тридцать ночей позади.': 'Thirty nights behind you.',
  'Заправка пережила отключения света, странных гостей и самую длинную ночь. Теперь это место на трассе знают все.': 'The station survived blackouts, strange visitors and the longest night. Everyone on this road knows the place now.',
  'ВЫРУЧКА': 'TAKINGS',
  'ЗА КАМПАНИЮ': 'FOR THE CAMPAIGN',
  'КЛИЕНТОВ': 'CUSTOMERS',
  'ЛУЧШАЯ СМЕНА': 'BEST SHIFT',
  'НАЧАТЬ КАМПАНИЮ ЗАНОВО': 'START THE CAMPAIGN AGAIN',
  'Выбрать уровень': 'Pick a level',
  'ПОВЕРНИТЕ ТЕЛЕФОН': 'ROTATE YOUR PHONE',
  'Ночная смена играется горизонтально': 'The night shift plays in landscape',
};
